### ISSUE TITLE
GB2312 support

### ISSUE THREAD

**Issue by lanbin45** [dankogai/js-base64#106]
Hello, thank you for this awesome lib firstly! But I've found this lib did not support decode base64 string with GB2312. And I did not find any npm packages support GB2313 decode.

Do you have plans to support GB2312?

**Comment by dankogai** [comment]
No.  Because that does not belong to JS layer.  From the point of view of JS, all `string` are Unicode (UTF-16 exactly speaking), even if it is embedded in the HTML file where `Content-type: text/html; charset=GB2313`  Your browser (user-agent, exactly speaking) decodes to Unicode BEFORE your script handles it.
