### ISSUE TITLE
NodeJS Issues

### ISSUE THREAD

**Issue by jasonmacer** [dankogai/js-base64#121]
Hello, I've been running 2.5.2 and just did a fresh install that pulled in 2.6.3 and I've run into an interesting issue.  

Here is my include:

const Base64 = require('js-base64').Base64;

And here is my usage:

let requiresEncoding = report.pdf  <<this is a 1 page pdf file>>
return Base64.encode(requiresEncoding);

v2.5.2 returns the correct base64 that is the (1) page pdf report

v2.6.2 returns a (3) page blank PDF.

If I put the base64 of each version into a text file, one is about 88kb (that would be version 2.5.2), and the other is 225kb (that would be version 2.6.2)

Am i missing a changed switch?  I'm also sure im going to be told to upgrade to the new 3.2.4, and I will, but I have a feeling i'm going to run into the same issue with this. 

Any help would be greatly appreciated.

Thanks,

**Comment by dankogai** [comment]
Looks like you are not using `Base64.encode` correctly.  It should be `Base64.btoa` because your source data IS NOT ENCODED IN UTF-8.   A small shell script below illustrates how `btoa` is used.  

Node.js does not have one but it has `buffer`.  `js-base64` used to use it but it was abondoned because it was causing too much trouble.

* https://github.com/dankogai/js-base64/issues/85

Try embedding files yourself.  Now change `binary` to `utf8`, `Base64.btoa` to `Base64.encode` and see what happed.

See Also:

* https://github.com/dankogai/js-base64#decode-vs-atob-and-encode-vs-btoa

```javascript
#!/usr/bin/env node
const {Base64} = require('js-base64');
const mimetype = 'application/octet-stream';
const path = process.argv[2];
if (typeof path !== 'string') {
    console.log(`USAGE: ${process.argv[1]} path/to/file-to-embed`);
    process.exit(-1);
}
const filename = path.split('/').pop();
require('fs').readFile(path, 'binary', (err, binstr) => {
    if (err) {
        return console.log(err);
    }
    const b64str = Base64.btoa(binstr);
    console.log(`<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>${filename}</title>
  </head>
  <body>
    <ul>
      <li><a href="data:${mimetype};base64,${b64str}">${filename}</a></li>
     </ul>
  </body>
</html>`);
});
```

**Comment by jasonmacer** [comment]
Thanks @dankogai I'm guessing you guys made that change after the 2.5.2 version. This weekend I'll upgrade and migrate to the Base64.atob() from the encode.
