### ISSUE TITLE
Base64.decode error

### ISSUE THREAD

**Issue by sashamirkovic** [dankogai/js-base64#36]
When I decode o562s4yhR0fEUtuRrlO3LBpMl1A58LYTFQsPxKPiGpA
Other decoders give: £¶³¡GGÄRÛ®S·,LP9ð¶Ä£â
Base64.decode gives: £¶³¡GGÄRۑ®S·,LP9ð¶ģâ

**Comment by alex-pex** [comment]
Same problem here (also related to #34 I think)

This test shows "different", because Base64.decode doesn't work properly
```js
  const text = 'iVBORw0KGgoAAAAN';
  console.log(Base64.decode(text));
  console.log(Base64.encode(Base64.decode(text)) === text ? 'same' : 'different');
```

The same test on PHP shows "same" because the PHP function works
```php
  $text = 'iVBORw0KGgoAAAAN';
  echo base64_decode($text);
  echo base64_encode(base64_decode($text)) === $text ? 'same' : 'different';
```

The Base64 text is the beginning of a image/png embedded as a data URI. I need to decode it before sending to the server.

**Comment by dankogai** [comment]
Use `Base64.atob()` instead of `Base64.decode()` and `Base64.btoa()` instead of `Base64.encode()`
