### ISSUE TITLE
error decoding

### ISSUE THREAD

**Issue by monteslu** [dankogai/js-base64#84]
for this string of base64 data:  `Y2UAAm9yQEPHkNtqWzCE9FswvTQ=`

this library decodes to 19 bytes, while `base64-js`, node's `Buffer` class, and browsers' `atob` implementation all give me 20 bytes.

**Comment by htaketani** [comment]
Hi, monteslu.
Perhaps, original source data of the base64 data is binary data string?
decode() of this library restores the data as utf8 string,
Some data was converted to utf8 character, and the total length became shorter.

Use atob() instead of decode() for binary data.

But, in Node.js, atob() of current version library may have a bug.
It seems that sometimes unnecessary null bytes are added to the end of restored data.

---
(in Japanese)

こんにちは、monteslu。
そのbase64データは、おそらく、バイナリデータ文字列をエンコードしたものではないでしょうか？
このライブラリのdecode()は、データをutf8文字列として復元するので、
一部のデータがutf8文字に変換されて、長さが短くなったのでしょう。

バイナリデータを扱う場合は、`Base64.decode()`の代わりに`Base64.atob()`を使ってください。
[.decode() vs .atob](https://github.com/dankogai/js-base64#decode-vs-atob-and-encode-vs-btoa)

しかし、Node.js環境でこのライブラリを使う場合、もしかすると現在のバージョンのatob()にはバグがあるかもしれません。
復元データの末尾に不要なnullが追加される場合があるようです。
